#Server Port
server:
  port: 8082
  
#App Specific
spring:
  application:
    name: Master Schedular Service
        
#Datasource Config
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1522:orcl
    username: system
    password: manager
    
#  datasource:  
#   driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/test
#    username: postgres
#    password: First#1234

#JPA Config  
  jpa:
    database: oracle
    show-sql: true
    hibernate:
      ddl-auto: update
#org.hibernate.dialect.PostgreSQL95Dialect
  sql:
    init:
      platform: oracle
      
#Date Time Formats      
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss


#Custom Properties
ms: 
  datetimeformat: yyyy/MM/ddTHH:mm:ss








 